#!/bin/sh /etc/rc.common
# Compatible with OpenWRT procd (15.05+). Reads YAML config from /etc/config/koiddns.

START=99
USE_PROCD=1

NAME=koiddns
PROG=/usr/bin/koiddns
CONFIG=/etc/config/koiddns

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --config "$CONFIG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "koiddns"
}
